# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Fins FAQ
tagline:             Things people ask on a stream chat, every single time.
url:                 http://kozzi.github.io/finsfaq
paginate:            1
baseurl:             "http://kozzi.github.io/finsfaq/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Charing Wong
  url:               https://twitter.com/kozzi
  email:             kozzi@thisisalie.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/kozzi/finsfaq

markdown:            kramdown
